# Предметы:
# 0
# 1
# 2
# 3
# 4
# 5
# 6
# 7
# 8
#
# Свойства:
# 0. Рост
# 1. Национальность
# 2. Номер дома
# 3. Домашнее животное
#
# Значения Свойств:
# 0
# 1
# 2
# 3
# 4
# 5
# 6
# 7
# 8

# Constraint format is c1{<prop>, <obj>, <value>}, indexes start w 0
# Constraint 1

c1{0, 0, 0}
c1{1, 1, 1}
c1{2, 2, 2}
c1{3, 3, 3}
c1{0, 4, 4}
c1{1, 5, 5}
c1{2, 6, 6}

# Constraint format is c2{{<prop1>, <val1>}, {<prop2>, <val2>}}, indexes start w 0
# Constraint 2
c2{{0, 0}, {1, 3}}
c2{{1, 1}, {0, 1}}
c2{{2, 2}, {3, 1}}
c2{{3, 3}, {2, 2}}

# Constraint format is c3{<side>, {<prop1>, <val1>}, {<prop2>, <val2>}}, indexes start w 0
# Constraint 3
c3{u, {0, 0}, {3, 4}}
c3{d, {0, 4}, {3, 2}}

# Constraint format is c4{<c3_1>, <c3_2>}, indexes start w 0
# Constraint 4
c4{{u, {0, 0}, {3, 4}}, {d, {0, 4}, {3, 2}}}

# NOTE: Additional constraints

